tests:
    "Pages should be fast enough":
        path: "/.*" # run the assertions for all HTTP requests
        assertions:
            - "main.wall_time < 1s" # wall clock time is less than 1s
            - "metrics.sql.queries.count < 200"
            - "main.peak_memory < 64MB"
            - "metrics.itop.queries.count < 5"

# Example metric counting how many times a function is called
metrics:
  itop.queries: # metric name
    label: "ITopClient::sendRequest() calls"
    matching_calls:
      php:
        - callee: '/ITopClient::sendRequest$/'

# Example scenarios, visit the home page, then user page
scenarios:
    Home page:
        - /
    User login page:
        - /user/login
