# This files can also be used locally :
# Running "drone exec" after downloading drone's CLI
# will install the site and run the full test task

# Defines where the builds takes place ( /test/oe_theme )
workspace:
  base: /test
  path: oe_theme

services:
  web:
    image: fpfis/php71-build:latest
    environment:
      - DOCUMENT_ROOT=/test/oe_theme
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

matrix:
  DRUPAL_VERSION:
    - 8.6.x

pipeline:
  npm-build:
    group: prepare
    image: node:latest
    commands: 
      - npm install
      - npm run build

  composer-install:
    group: prepare
    image: fpfis/php71-build
    # Allows for cross build caching ( fpfis/php71-build stores drush and composer caches in /cache )
    volumes:
      - /cache:/cache
    commands:
      - composer require --dev webflo/drupal-core-require-dev:${DRUPAL_VERSION=8.6.x}

  # Perform a security check on composer deps ( https://github.com/phpdrone/composer-sa-checker )
  composer-sa-check:
    image: phpdrone/composer-sa-checker
    lock_file: composer.lock

  site-install:
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/run drupal:site-setup
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/behat

  before-release:
    image: fpfis/php71-build
    commands:
      - ./scripts/drone/create-release-tarball.sh
    when:
      matrix:
        DRUPAL_VERSION: 8.6.x
      event: tag

  github-release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: oe_theme-${DRONE_TAG}.tar.gz
    when:
      matrix:
        DRUPAL_VERSION: 8.6.x
      event: tag

  slack-notify-release:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: ci
    username: oebot
    icon_url: https://avatars0.githubusercontent.com/u/35874187?.png
    when:
      event: [ tag ]
      status: [ success, failure ]
      matrix:
        DRUPAL_VERSION: 8.6.x
    template: >
      {{#success build.status}}
        OpenEuropa component ${DRONE_REPO_NAME} <${DRONE_REPO_LINK}|${DRONE_TAG}> has been <{{build.link}}|released>.
      {{else}}
        OpenEuropa component ${DRONE_REPO_NAME} <${DRONE_REPO_LINK}|${DRONE_TAG}> release <{{build.link}}|failed>.
      {{/success}}
