workspace:
  base: /test
  path: oe_theme

services:
  web:
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    environment:
      - DOCUMENT_ROOT=/test/oe_theme
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  sparql:
    image: openeuropa/triple-store-dev
    pull: true
    environment:
      - SPARQL_UPDATE=true
      - DBA_PASSWORD=dba
  selenium:
    image: selenium/standalone-chrome:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug

pipeline:
  npm-build:
    group: prepare
    image: node:9.5.0
    commands:
      - npm install --unsafe-perm
      - NODE_ENV=production npm run build

  composer-install:
    group: prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress

  composer-update-lowest:
    group: post-prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    volumes:
      - /cache:/cache
    commands:
      - composer update --prefer-lowest --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  site-install:
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
      - ./vendor/bin/behat --strict

  before-release:
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
      - ./vendor/bin/run release:create-archive --tag=${DRONE_TAG}
    when:
      event: tag

  github-release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: oe_theme-${DRONE_TAG}.tar.gz
    when:
      event: tag
      matrix:
        COMPOSER_BOUNDARY: highest

matrix:
  PHP_VERSION:
    - 7.1
    - 7.2
  COMPOSER_BOUNDARY:
    - lowest
    - highest
